language: generic

install:
- npm install -g ajv-cli

script:
# Versions and changelogs
- |
  if [[ "$TRAVIS_TAG" != "" ]]; then
    fgrep "**$TRAVIS_TAG**" README.md
    fgrep "/$TRAVIS_TAG/" utils/testsuite-schema.json
  fi
- |
  last_commit="${TRAVIS_PULL_REQUEST_SHA:-${TRAVIS_TAG:-${TRAVIS_COMMIT}}}"
  echo "$last_commit"
  git show --format=%B --quiet "$last_commit" > /tmp/last-commit-message
  cat /tmp/last-commit-message
- |
  if fgrep '[changelog skip]' /tmp/last-commit-message > /dev/null; then
    echo "Skip changelog checker..."
  elif [[ "$TRAVIS_TAG" != "" ]]; then
    ! fgrep -i "to be released" CHANGES.md
  elif [[ "$TRAVIS_COMMIT_RANGE" != "" ]]; then
    {
      git diff --name-only "$TRAVIS_COMMIT_RANGE" || \
      git diff --name-only "$TRAVIS_COMMIT^..$TRAVIS_COMMIT"
    } > /tmp/changed-files.txt
    cat /tmp/changed-files.txt
    fgrep CHANGES.md /tmp/changed-files.txt
  fi

# JSON test files
- |
  for j in testsuite/*.json; do
    ajv validate -s utils/testsuite-schema.json -d "$j"
  done
